### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by kudzuu** [kriasoft/graphql-starter#294]
.yarn/$$virtual/validator-fluent-virtual-a29a89fa3c/0/cache/validator-fluent-npm-0.4.1-9e838a2afa-0616fa507c.zip/node_modules/validator-fluent/lib/validate.js:48
➤ YN0000:   code = 422;
➤ YN0000:        ^
➤ YN0000: 
➤ YN0000: SyntaxError: Unexpected token =
➤ YN0000:     at Module._compile (internal/modules/cjs/loader.js:723:23)
➤ YN0000:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
➤ YN0000:     at Module.load (internal/modules/cjs/loader.js:653:32)

➤ YN0000:     at Module._extensions..js (internal/modules/cjs/loader.js:789:10)`

**Comment by ReedME** [comment]
I recieve this same issue when running yarn api:start
https://media.discordapp.net/attachments/649961503256084504/824240368929341460/error.png

**Comment by ReedME** [comment]
Check to ensure you are running Node V14, this solved the issue for me @kudzuu
